image:
  file: .gitpod/.gitpod.Dockerfile

# ddev and composer are running as part of the prebuild
# when starting a workspace all docker images are ready
tasks:
  - name: moodle
    init: |
      # Moodle needs database=mariadb:10.7. DDEV default to 10.4 which is not compatible
      ddev config --composer-root=public --create-docroot --docroot=public --webserver-type=apache-fpm --database=mariadb:10.7
      yes | ddev start
      # (must after ddev config) install selenium chrome plugin https://github.com/ddev/ddev-selenium-standalone-chrome
      ddev get ddev/ddev-selenium-standalone-chrome
      # enable vnc at port 7900, password: `secret`. https://github.com/ddev/ddev-selenium-standalone-chrome
      # 5900 is really for outside world like mac "ScreenSharing" or "RealVNC" client
      sed -i "/#ports/ { s#.*#    ports:# }" .ddev/docker-compose.selenium-chrome.yaml
      sed -i "/5900:5900/ { s#.*#      - 5900:5900\n      - 7900:7900# }" .ddev/docker-compose.selenium-chrome.yaml
      # before was composer create, now use clone to always have newest source and keep git log
      # NOTE: MUST `ddev composer create`, which is a special ddev command! can not do `ddev composer create-project`
      ddev composer create moodle/moodle --keep-vcs -y
      ddev exec 'php public/admin/cli/install.php --non-interactive --agree-license --wwwroot=$DDEV_PRIMARY_URL --dbtype=mariadb --dbhost=db --dbname=db --dbuser=db --dbpass=db --fullname="DDEV Moodle Demo" --shortname=Demo --adminpass=password'
      ## update config.php ##
      # remove the setup.php line from config.php
      sed -i '/\/lib\/setup.php/d' public/config.php
      ### setup for phpunit ###
      ## phpunit part ##
      echo "\$CFG->phpunit_dataroot  = realpath(dirname(__DIR__)) . '/phpunitdata';" >> public/config.php 
      echo "\$CFG->phpunit_prefix = 't_';" >> public/config.php
      ## behat part ##
      echo "\$CFG->behat_prefix = 'bht_';" >> public/config.php
      # MUST be web:80 - since behat.yml is READ & EXECUTED by selenium-chrome, so wwwroot is in the point of view from SELENIUM, not web container NOR host machine itself! 
      echo "\$CFG->behat_wwwroot = 'http://web';" >> public/config.php
      echo "\$CFG->behat_dataroot = '/var/www/html/bht_moodledata';" >> public/config.php
      # enable chrome profile since default was firefox only https://moodledev.io/general/development/tools/behat/running#installation
      # notice path name is all in container perspective hence "/var/www/html", not host machine
      git clone https://github.com/andrewnicols/moodle-browser-config
      echo "require_once('/var/www/html/moodle-browser-config/init.php');" >> public/config.php
      # put require_once back - must be at the end of file
      echo "require_once(__DIR__ . '/lib/setup.php');" >> public/config.php
      ## update config.php END ##
      # initiate behat  
      ddev php public/admin/tool/behat/cli/init.php
      # for Jetbrains remote development/gateway (not sure due to gateway) ###
      # "Preferences | PHP | Test Frameworks" can save php-test-framework.xml to .idea folder, but NOT WORKING after restart IDE backend
      #   Current workaround: PhpStorm seems to "guess" behat config location (not sure due to DDEV), so even WITHOUT any config in Test Frameworks
      #   it first "guess" public/behat.yml(.dist) (should due to ddev? since it is not project root, it is "composer root")
      #   hence solution is to create a symlink to the real config file
      #   NOTE: phpunit not needed since it is already at "composer root" /public
      ln -s ../bht_moodledata/behatrun/behat/behat.yml public/behat.yml
      # fix generated behat.dist.yml incorrectly use localhost assumption for base_url
      sed -i "/base_url:/ { s#.*#      base_url: 'http://web:80'# }" public/behat.yml
      # same for all wd_host keys - ex: chrome (not chromedriver) key wd_host
      sed -i "/wd_host:/ { s#.*#        wd_host: 'http://selenium-chrome:4444/wd/hub'# }" public/behat.yml
      ## behat END ##
      # initiate phpunit  
      ddev php public/admin/tool/phpunit/cli/init.php
    command: |
      yes| ddev start
      # PREBUILD problem - url at config.php will be the old prebuild workspace url, hence must append every time we start
      # MUST happen before require_once, hence can not simply append. Here use sed to find and replace
      sed -i "/\$CFG->wwwroot/ { s#.*#\$CFG->wwwroot   = '$(gp url 8080)';# }" public/config.php 
      # give basic info: ONLY works for vscode or jetbrains IDE - NOT "browser terminal" 
      #   hence if use "browser terminal", must manually use "gp tasks list" to see this message... 
      #   https://www.gitpod.io/docs/references/ides-and-editors/browser-terminal#managing-workspace-tasks
      echo "vnc exposed at port $(gp url 5900), password: secret"
      echo "example behat command to run - MUST be inside container: ddev ssh;cd public;vendor/bin/behat -v --profile chrome --config behat.yml  ./user/tests/behat/filter_idnumber.feature" 
      ddev launch /login 

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true

# enable useful plugins
jetbrains:
  phpstorm:
    plugins:
      - com.intellij.lang.jsgraphql
      - org.sonarlint.idea
      - com.intellij.ml.llm
      - com.sourcegraph.jetbrains
      - com.github.lppedd.idea-conventional-commit
      - de.php_perfect.intellij.ddev
      #  inline blame not working on jetbrains client, but status bar still okay
      - zielu.gittoolbox
      - com.kalessil.phpStorm.phpInspectionsEA
      # NEVER need to turn on, doc purpose - vim is at jetbrains client! not backend! 
      #- IdeaVIM
      # sometimes caused workspace with jetbrains not able to start, hence comment out
      # prebuilds:
      # version: stable
